package vn.itt.msales.entity;
// Generated Sep 10, 2015 1:21:05 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.sql.Time;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import vn.itt.msales.common.json.validator.MsalesValidator;

/**
 * CompanyConstant generated by hbm2java
 */
@Entity
@Table(name = "company_constant"
)
public class CompanyConstant implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)

    private Integer id;
    @Transient
    private Integer companyId;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @NotNull(message = MsalesValidator.VERSION_COMPANY_ID_NULL)
    @JoinColumn(name = "COMPANY_ID", nullable = false)
    private Company companys;

    public Company getCompanys() {
        return companys;
    }

    public void setCompanys(Company companys) {
        this.companys = companys;
    }

    @Column(name = "PERIOD_GET_POSITION", nullable = false)
    private Integer periodGetPosition;
    @Column(name = "PERIOD_SEND_POSITION", nullable = false)
    private Integer periodSendPosition;
    @Column(name = "DISTANCE", nullable = false)
    private Integer distance;
    @Column(name = "MIN_DISTANCE", nullable = false)
    private Integer minDistance;

    
    @Column(name = "TIMESHEET_FROM", nullable = false, length = 8)
    private Time timesheetFrom;

    
    @Column(name = "MORNING_FROM", nullable = false, length = 8)
    private Time morningFrom;

   
    @Column(name = "MORNING_TO", nullable = false, length = 8)
    private Time morningTo;

    
    @Column(name = "EVENING_FROM", nullable = false, length = 8)
    private Time eveningFrom;

   
    @Column(name = "EVENING_TO", nullable = false, length = 8)
    private Time eveningTo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_AT", nullable = false, length = 19)
    private Date createdAt;
    @Column(name = "CREATED_USER", nullable = false)
    private Integer createdUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_AT", length = 19)
    private Date updatedAt;
    @Column(name = "UPDATED_USER", nullable = false)
    private Integer updatedUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DELETED_AT", length = 19)
    private Date deletedAt;
    @Column(name = "DELETED_USER", nullable = false)
    private Integer deletedUser;
    
    @Transient
    private long serverTime;
    
    public long getServerTime() {
        return serverTime;
    }

    public void setServerTime(long serverTime) {
        this.serverTime = serverTime;
    }
    
    @Transient
    private String appVersion;

    public String getAppVersion() {
        return appVersion;
    }

    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }        

    public CompanyConstant() {
    }

    public CompanyConstant(Integer companyId, Integer periodGetPosition, Integer periodSendPosition, Integer distance, Integer minDistance, Time timesheetFrom, Time morningFrom, Time morningTo, Time eveningFrom, Time eveningTo, Date createdAt, Integer createdUser, Integer updatedUser, Integer deletedUser) {
        this.companyId = companyId;
        this.periodGetPosition = periodGetPosition;
        this.periodSendPosition = periodSendPosition;
        this.distance = distance;
        this.minDistance = minDistance;
        this.timesheetFrom = timesheetFrom;
        this.morningFrom = morningFrom;
        this.morningTo = morningTo;
        this.eveningFrom = eveningFrom;
        this.eveningTo = eveningTo;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedUser = updatedUser;
        this.deletedUser = deletedUser;
    }

    public CompanyConstant(Integer companyId, Integer periodGetPosition, Integer periodSendPosition, Integer distance, Integer minDistance, Time timesheetFrom, Time morningFrom, Time morningTo, Time eveningFrom, Time eveningTo, Date createdAt, Integer createdUser, Date updatedAt, Integer updatedUser, Date deletedAt, Integer deletedUser) {
        this.companyId = companyId;
        this.periodGetPosition = periodGetPosition;
        this.periodSendPosition = periodSendPosition;
        this.distance = distance;
        this.minDistance = minDistance;
        this.timesheetFrom = timesheetFrom;
        this.morningFrom = morningFrom;
        this.morningTo = morningTo;
        this.eveningFrom = eveningFrom;
        this.eveningTo = eveningTo;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedAt = updatedAt;
        this.updatedUser = updatedUser;
        this.deletedAt = deletedAt;
        this.deletedUser = deletedUser;
    }

    @JsonIgnore
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @JsonIgnore
    public Integer getCompanyId() {
        return this.companyId;
    }

    @JsonSetter
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
        if (companyId != null) {
            Company company = new Company();
            company.setId(this.getCompanyId());
            this.companys = company;
        }
    }

    public Integer getPeriodGetPosition() {
        return this.periodGetPosition;
    }

    public void setPeriodGetPosition(Integer periodGetPosition) {
        this.periodGetPosition = periodGetPosition;
    }

    public Integer getPeriodSendPosition() {
        return this.periodSendPosition;
    }

    public void setPeriodSendPosition(Integer periodSendPosition) {
        this.periodSendPosition = periodSendPosition;
    }

    public Integer getDistance() {
        return this.distance;
    }

    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    public Integer getMinDistance() {
        return this.minDistance;
    }

    public void setMinDistance(Integer minDistance) {
        this.minDistance = minDistance;
    }

    public Time getMorningFrom() {
        return morningFrom;
    }

    public void setMorningFrom(Time morningFrom) {
        this.morningFrom = morningFrom;
    }

    public Time getMorningTo() {
        return morningTo;
    }

    public void setMorningTo(Time morningTo) {
        this.morningTo = morningTo;
    }

    public Time getEveningFrom() {
        return eveningFrom;
    }

    public void setEveningFrom(Time eveningFrom) {
        this.eveningFrom = eveningFrom;
    }

    public Time getEveningTo() {
        return eveningTo;
    }

    public void setEveningTo(Time eveningTo) {
        this.eveningTo = eveningTo;
    }

  
  

    public Time getTimesheetFrom() {
        return timesheetFrom;
    }

    public void setTimesheetFrom(Time timesheetFrom) {
        this.timesheetFrom = timesheetFrom;
    }

    @JsonIgnore
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @JsonIgnore
    public Integer getCreatedUser() {
        return this.createdUser;
    }

    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    @JsonIgnore
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @JsonIgnore
    public Integer getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    @JsonIgnore
    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    @JsonIgnore
    public Integer getDeletedUser() {
        return this.deletedUser;
    }

    public void setDeletedUser(Integer deletedUser) {
        this.deletedUser = deletedUser;
    }

    @JsonIgnore
    @Transient
    private Integer hourIn;
    
    @JsonIgnore
    @Transient
    private Integer minutesIn;
    
    @JsonIgnore
    @Transient
    private Integer hourMorStart;
    
    @JsonIgnore
    @Transient
    private Integer minuteMorStart;
    
    @JsonIgnore
    @Transient
    private Integer hourMorEnd;
    
    @JsonIgnore
    @Transient
    private Integer minuteMorEnd;
    
    @JsonIgnore
    @Transient
    private Integer hourEvenStart;
    
    @JsonIgnore
    @Transient
    private Integer minuteEvenStart;
    
    @JsonIgnore
    @Transient
    private Integer hourEvenEnd;
    
    @JsonIgnore
    @Transient
    private Integer minuteEvenEnd;

    public Integer getHourIn() {
        return hourIn;
    }

    public void setHourIn(Integer hourIn) {
        this.hourIn = hourIn;
    }

    public Integer getMinutesIn() {
        return minutesIn;
    }

    public void setMinutesIn(Integer minutesIn) {
        this.minutesIn = minutesIn;
    }

    public Integer getHourMorStart() {
        return hourMorStart;
    }

    public void setHourMorStart(Integer hourMorStart) {
        this.hourMorStart = hourMorStart;
    }

    public Integer getMinuteMorStart() {
        return minuteMorStart;
    }

    public void setMinuteMorStart(Integer minuteMorStart) {
        this.minuteMorStart = minuteMorStart;
    }

    public Integer getHourMorEnd() {
        return hourMorEnd;
    }

    public void setHourMorEnd(Integer hourMorEnd) {
        this.hourMorEnd = hourMorEnd;
    }

    public Integer getMinuteMorEnd() {
        return minuteMorEnd;
    }

    public void setMinuteMorEnd(Integer minuteMorEnd) {
        this.minuteMorEnd = minuteMorEnd;
    }

    public Integer getHourEvenStart() {
        return hourEvenStart;
    }

    public void setHourEvenStart(Integer hourEvenStart) {
        this.hourEvenStart = hourEvenStart;
    }

    public Integer getMinuteEvenStart() {
        return minuteEvenStart;
    }

    public void setMinuteEvenStart(Integer minuteEvenStart) {
        this.minuteEvenStart = minuteEvenStart;
    }

    public Integer getHourEvenEnd() {
        return hourEvenEnd;
    }

    public void setHourEvenEnd(Integer hourEvenEnd) {
        this.hourEvenEnd = hourEvenEnd;
    }

    public Integer getMinuteEvenEnd() {
        return minuteEvenEnd;
    }

    public void setMinuteEvenEnd(Integer minuteEvenEnd) {
        this.minuteEvenEnd = minuteEvenEnd;
    }

}
