package vn.itt.msales.entity;
// Generated Jun 11, 2015 10:37:14 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
import vn.itt.msales.common.json.validator.MsalesValidator;

/**
 * POS generated by hbm2java
 */
@Entity
@Table(name = "`pos`"
)
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@JsonFilter("JSONFILTER")
public class POS implements java.io.Serializable {

    private static final long serialVersionUID = 8753956560886611521L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "SEQ_ID")
    @SequenceGenerator(name = "SEQ_ID", sequenceName = "SEQ_POS_ID")
    private Integer id;

    @NotEmpty(message = MsalesValidator.POS_POS_CODE_EMPTY)
    @Column(name = "POS_CODE", nullable = false, length = 256)
    private String posCode;

    @NotNull(message = MsalesValidator.POS_NAME_NULL)
    @NotEmpty(message = MsalesValidator.POS_NAME_EMPTY)
    @Column(name = "NAME", nullable = false, length = 256)
    private String name;
    
    @Transient
    private String[] images;

    public String[] getImages() {
        return images;
    }
    
    @Transient
    private String image;

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }
    

    @JsonSetter
    public void setImages(String[] images) {
        this.images = images;
    }


    @Transient
    private Integer channelId;

    @Transient
    private Integer locationId;

    @Transient
    private Integer statusId;

    //more info
    @NotNull(message = MsalesValidator.POS_CHANNEL_ID_NULL)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CHANNEL_ID", nullable = false)
    @JsonIgnoreProperties(value = {"parents", "companys", "statuss", "channelTypes", "code",
        "isSalePoint", "address", "contactPersonName", "tel", "fax", "email", "lat", "lng", "note"})
    private Channel channels;

    public Channel getChannels() {
        return channels;
    }

    public void setChannels(Channel channels) {
        this.channels = channels;
    }

    @NotNull(message = MsalesValidator.POS_ADDRESS_NULL)
    @NotEmpty(message = MsalesValidator.POS_ADDRESS_EMPTY)
    @Column(name = "ADDRESS", nullable = false, length = 128)
    private String address;

    @NotNull(message = MsalesValidator.POS_LOCATION_ID_NULL)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "LOCATION_ID", nullable = false)
    @JsonIgnoreProperties(value = {"locationTypes", "code", "note", "lat", "lng"})
    private Location locations;

    public Location getLocations() {
        return locations;
    }

    public void setLocations(Location locations) {
        this.locations = locations;
    }
    
    @NotNull(message = MsalesValidator.POS_STATUS_ID_NULL)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "STATUS_ID", nullable = false)
    @JsonIgnoreProperties(value = {"statusTypes", "value"})
    private Status statuss;

    public Status getStatuss() {
        return statuss;
    }

    public void setStatuss(Status statuss) {
        this.statuss = statuss;
    }

    @NotNull(message = MsalesValidator.POS_HIERARCHY_NULL)
    @Column(name = "HIERARCHY", nullable = false)
    private Integer hierarchy;

    @Column(name = "OWNER_NAME", length = 100)
    private String ownerName;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "BIRTHDAY", length = 10)
    @JsonFormat(pattern = "dd/MM/yyyy", shape = JsonFormat.Shape.STRING, timezone = "GMT+7")
    private Date birthday;

    @Column(name = "OWNER_CODE", length = 100)
    private String ownerCode;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OWNER_CODE_DATE", length = 10)
    @JsonFormat(pattern = "dd/MM/yyyy", shape = JsonFormat.Shape.STRING, timezone = "GMT+7")

    private Date ownerCodeDate;
    @Column(name = "OWNER_CODE_LOCATION", length = 256)
    private String ownerCodeLocation;
    @Column(name = "TEL", length = 20)
    private String tel;
    @Column(name = "MOBILE", length = 20)
    private String mobile;
    @Column(name = "OTHER_TEL", length = 50)
    private String otherTel;
    @Column(name = "FAX", length = 20)
    private String fax;
    @Column(name = "EMAIL", length = 50)
    private String email;
    @Column(name = "WEBSITE", length = 256)
    private String website;
    @Column(name = "GPKD", length = 30)
    private String gpkd;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "GPKD_DATE", length = 10)
    @JsonFormat(pattern = MsalesValidator.DATE_FORMAT_SHORT, shape = JsonFormat.Shape.STRING, timezone = MsalesValidator.GMT)
    private Date gpkdDate;
    @Column(name = "GPKD_LOCATION", length = 100)
    private String gpkdLocation;
    
    @Column(name = "FREQUENCY")
    private Integer frequency;
    @Column(name = "DAY_OF_WEEK")
    private Integer dayOfWeek;
    @Column(name = "START_DATE", length = 10)
    @Temporal(TemporalType.TIMESTAMP)
    private Date startDate;
    
    @Column(name = "NOTE", length = 256)
    private String note;

    @NotNull(message = MsalesValidator.POS_LAT_NULL)
    @Column(name = "LAT", nullable = false, precision = 24, scale = 15)
    private BigDecimal lat;

    @NotNull(message = MsalesValidator.POS_LNG_NULL)
    @Column(name = "LNG", nullable = false, precision = 24, scale = 15)
    private BigDecimal lng;

    @NotNull(message = MsalesValidator.POS_IS_ACTIVE_NULL)
    @Column(name = "IS_ACTIVE", nullable = false)
    private Integer isActive;

    @NotNull(message = MsalesValidator.POS_BEGIN_AT)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "BEGIN_AT", nullable = false, length = 19)
    @JsonFormat(pattern = MsalesValidator.DATE_FORMAT_LONG, shape = JsonFormat.Shape.STRING, timezone = MsalesValidator.GMT)
    private Date beginAt;

    @NotNull(message = MsalesValidator.POS_END_AT)
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "END_AT", nullable = false, length = 19)
    @JsonFormat(pattern = MsalesValidator.DATE_FORMAT_LONG, shape = JsonFormat.Shape.STRING, timezone = MsalesValidator.GMT)
    private Date endAt;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_AT", nullable = false, length = 19)
    private Date createdAt;

    @Column(name = "CREATED_USER", nullable = false)
    @NotNull(message = MsalesValidator.CREATED_USER_NULL)
    private Integer createdUser;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_AT", length = 19)
    @JsonIgnore
    private Date updatedAt;

    @Column(name = "UPDATED_USER", nullable = false)
    @NotNull(message = MsalesValidator.UPDATED_USER_NULL)
    private Integer updatedUser;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DELETED_AT", length = 19)
    @JsonIgnore
    private Date deletedAt;

    @Column(name = "DELETED_USER", nullable = false)
    @NotNull(message = MsalesValidator.DELETED_USER_NULL)
    private Integer deletedUser;
    
    @Transient 
    private Integer provinceId;
     
    @Transient
    private Integer districtId;
    
    @Transient
    private Integer wardId;

    public POS() {
    }

    public POS(String name, Integer channelId, String address, String street, Integer locationId, Integer statusId, Integer hierarchy, BigDecimal lat, BigDecimal lng, Integer isActive, Date beginAt, Date endAt, Date createdAt, Integer createdUser, Date updatedAt, Integer updatedUser, Date deletedAt, Integer deletedUser) {
        this.name = name;
        this.channelId = channelId;
        this.address = address;
        this.locationId = locationId;
        this.statusId = statusId;
        this.hierarchy = hierarchy;
        this.lat = lat;
        this.lng = lng;
        this.isActive = isActive;
        this.beginAt = beginAt;
        this.endAt = endAt;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedAt = updatedAt;
        this.updatedUser = updatedUser;
        this.deletedAt = deletedAt;
        this.deletedUser = deletedUser;
    }

    public POS(String name, Integer channelId, String address, String street, Integer locationId, Integer statusId, Integer hierarchy, String ownerName, Date birthday, String ownerCode, Date ownerCodeDate, String ownerCodeLocation, String tel, String mobile, String otherTel, String fax, String email, String website, String gpkd, Date gpkdDate, String gpkdLocation, String note, BigDecimal lat, BigDecimal lng, Integer isActive, Date beginAt, Date endAt, Date createdAt, Integer createdUser, Date updatedAt, Integer updatedUser, Date deletedAt, Integer deletedUser) {
        this.name = name;
        this.channelId = channelId;
        this.address = address;
        this.locationId = locationId;
        this.statusId = statusId;
        this.hierarchy = hierarchy;
        this.ownerName = ownerName;
        this.birthday = birthday;
        this.ownerCode = ownerCode;
        this.ownerCodeDate = ownerCodeDate;
        this.ownerCodeLocation = ownerCodeLocation;
        this.tel = tel;
        this.mobile = mobile;
        this.otherTel = otherTel;
        this.fax = fax;
        this.email = email;
        this.website = website;
        this.gpkd = gpkd;
        this.gpkdDate = gpkdDate;
        this.gpkdLocation = gpkdLocation;
        this.note = note;
        this.lat = lat;
        this.lng = lng;
        this.isActive = isActive;
        this.beginAt = beginAt;
        this.endAt = endAt;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedAt = updatedAt;
        this.updatedUser = updatedUser;
        this.deletedAt = deletedAt;
        this.deletedUser = deletedUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPosCode() {
        return posCode;
    }

    public void setPosCode(String posCode) {
        this.posCode = posCode;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @JsonIgnore
    public Integer getChannelId() {
        return this.channelId;
    }

    @JsonSetter
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
        if (channelId != null) {
            Channel channel = new Channel();
            channel.setId(this.channelId);
            this.channels = channel;
        }

    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @JsonIgnore
    public Integer getLocationId() {
        return this.locationId;
    }

    @JsonSetter
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
        if (locationId != null) {
            Location location = new Location();
            location.setId(this.locationId);
            this.locations = location;
        }
    }

    @JsonIgnore
    public Integer getStatusId() {
        return this.statusId;
    }

    @JsonSetter
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
        if (statusId != null) {
            Status status = new Status();
            status.setId(this.statusId);
            this.statuss = status;
        }

    }

    public Integer getHierarchy() {
        return this.hierarchy;
    }

    public void setHierarchy(int hierarchy) {
        this.hierarchy = hierarchy;
    }

    public String getOwnerName() {
        return this.ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getOwnerCode() {
        return this.ownerCode;
    }

    public void setOwnerCode(String owerCode) {
        this.ownerCode = owerCode;
    }

    public Date getOwnerCodeDate() {
        return this.ownerCodeDate;
    }

    public void setOwnerCodeDate(Date owerCodeDate) {
        this.ownerCodeDate = owerCodeDate;
    }

    public String getOwnerCodeLocation() {
        return this.ownerCodeLocation;
    }

    public void setOwnerCodeLocation(String ownerCodeLocation) {
        this.ownerCodeLocation = ownerCodeLocation;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getOtherTel() {
        return this.otherTel;
    }

    public void setOtherTel(String otherTel) {
        this.otherTel = otherTel;
    }

    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getGpkd() {
        return this.gpkd;
    }

    public void setGpkd(String gpkd) {
        this.gpkd = gpkd;
    }

    public Date getGpkdDate() {
        return this.gpkdDate;
    }

    public void setGpkdDate(Date gpkdDate) {
        this.gpkdDate = gpkdDate;
    }

    public String getGpkdLocation() {
        return this.gpkdLocation;
    }

    public void setGpkdLocation(String gpkdLocation) {
        this.gpkdLocation = gpkdLocation;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    public Integer getDayOfWeek() {
        return dayOfWeek;
    }

    public void setDayOfWeek(Integer dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public BigDecimal getLat() {
        return this.lat;
    }

    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    public BigDecimal getLng() {
        return this.lng;
    }

    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    public Integer getIsActive() {
        return this.isActive;
    }

    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }

    public Date getBeginAt() {
        return this.beginAt;
    }

    public void setBeginAt(Date beginAt) {
        this.beginAt = beginAt;
    }

    public Date getEndAt() {
        return this.endAt;
    }

    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Integer getCreatedUser() {
        return this.createdUser;
    }

    @JsonSetter
    public void setCreatedUser(int createdUser) {
        this.createdUser = createdUser;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @JsonIgnore
    public Integer getUpdatedUser() {
        return this.updatedUser;
    }

    @JsonSetter
    public void setUpdatedUser(int updatedUser) {
        this.updatedUser = updatedUser;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    @JsonIgnore
    public Integer getDeletedUser() {
        return this.deletedUser;
    }

    @JsonSetter
    public void setDeletedUser(int deletedUser) {
        this.deletedUser = deletedUser;
    }

    //DuanND
    @Transient
    private Integer isVisited;
    @Transient
    private Date timeCared;
    @Transient
    private Date timeSale;
    @Transient 
    private Date timeDelivery;

	public Integer getIsVisited() {
		return isVisited;
	}

	public void setIsVisited(Integer isVisited) {
		this.isVisited = isVisited;
	}

	public Date getTimeCared() {
		return timeCared;
	}

	public void setTimeCared(Date timeCared) {
		this.timeCared = timeCared;
	}

	public Date getTimeSale() {
		return timeSale;
	}

	public void setTimeSale(Date timeSale) {
		this.timeSale = timeSale;
	}

	public Date getTimeDelivery() {
		return timeDelivery;
	}

	public void setTimeDelivery(Date timeDelivery) {
		this.timeDelivery = timeDelivery;
	}
    @Transient
    private String nameNVCS;

	public String getNameNVCS() {
		return nameNVCS;
	}

	public void setNameNVCS(String nameNVCS) {
		this.nameNVCS = nameNVCS;
	}

    /**
     * @return the districtId
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * @param districtId the districtId to set
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * @return the wardId
     */
    public Integer getWardId() {
        return wardId;
    }

    /**
     * @param wardId the wardId to set
     */
    public void setWardId(Integer wardId) {
        this.wardId = wardId;
    }

    /**
     * @return the provinceId
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * @param provinceId the provinceId to set
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }
    @Transient
    private User userCreated;

    @JsonIgnoreProperties(value = {"statuss","password","birthday", "monitoringUsers",
        "employerUserId", "isActive", "activeCode", "employerType",
        "useEvoucher", "statusId", "locations", "username", "sex", "email",
        "yahooId", "skypeId", "isdn", "tel", "address", "note",
        "ipLastLogin", "updatedAt", "updatedUser", "employerUsers",
        "createdUser", "companys"})
	public User getUserCreated() {
		return userCreated;
	}

	public void setUserCreated(User userCreated) {
		this.userCreated = userCreated;
	}
    @Transient
    private String quanHuyen;
    @Transient
    private String tinhThanh;

	public String getQuanHuyen() {
		return quanHuyen;
	}

	public void setQuanHuyen(String quanHuyen) {
		this.quanHuyen = quanHuyen;
	}

	public String getTinhThanh() {
		return tinhThanh;
	}

	public void setTinhThanh(String tinhThanh) {
		this.tinhThanh = tinhThanh;
	}
    
}
