package vn.itt.msales.entity;
// Generated Oct 9, 2015 3:36:35 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * PromotionRangeAward generated by hbm2java
 */
@Entity
@Table(name = "PROMOTION_RANGE_AWARD"
)
public class PromotionRangeAward implements java.io.Serializable {

    private static final long serialVersionUID = 6358835714922376120L;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    private Integer id;
    @Column(name = "PROMOTION_NEXT_STATUS")
    private Integer promotionNextStatus;
    @Column(name = "PROMOTION_R01")
    private Integer promotionR01;
    @Column(name = "PROMOTION_V01")
    private Integer promotionV01;
    @Column(name = "PROMOTION_R02")
    private Integer promotionR02;
    @Column(name = "PROMOTION_V02")
    private Integer promotionV02;
    @Column(name = "PROMOTION_R03")
    private Integer promotionR03;
    @Column(name = "PROMOTION_V03")
    private Integer promotionV03;
    @Column(name = "PROMOTION_R04")
    private Integer promotionR04;
    @Column(name = "PROMOTION_V04")
    private Integer promotionV04;
    @Column(name = "PROMOTION_R05")
    private Integer promotionR05;
    @Column(name = "PROMOTION_V05")
    private Integer promotionV05;
    @Transient
    private Integer statusId;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "STATUS_ID", nullable = false)
    private Status statuss;

    public Status getStatuss() {
        return statuss;
    }

    public void setStatuss(Status statuss) {
        this.statuss = statuss;
    }

    @Transient
    private Integer promotionId;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PROMOTION_ID", nullable = false)
    private Promotion promotions;

    public Promotion getPromotions() {
        return promotions;
    }

    public void setPromotions(Promotion promotions) {
        this.promotions = promotions;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_AT", nullable = false, length = 19)
    private Date createdAt;
    @Column(name = "CREATED_USER", nullable = false)
    private Integer createdUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_AT", length = 19)
    private Date updatedAt;
    @Column(name = "UPDATED_USER", nullable = false)
    private Integer updatedUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DELETED_AT", length = 19)
    private Date deletedAt;
    @Column(name = "DELETED_USER", nullable = false)
    private Integer deletedUser;

    public PromotionRangeAward() {
    }

    public PromotionRangeAward(Integer statusId, Integer promotionId, Date createdAt, Integer createdUser, Integer updatedUser, Integer deletedUser) {
        this.statusId = statusId;
        this.promotionId = promotionId;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedUser = updatedUser;
        this.deletedUser = deletedUser;
    }

    public PromotionRangeAward(Integer promotionNextStatus, Integer promotionR01, Integer promotionV01, Integer promotionR02, Integer promotionV02, Integer promotionR03, Integer promotionV03, Integer promotionR04, Integer promotionV04, Integer promotionR05, Integer promotionV05, Integer statusId, Integer promotionId, Date createdAt, Integer createdUser, Date updatedAt, Integer updatedUser, Date deletedAt, Integer deletedUser) {
        this.promotionNextStatus = promotionNextStatus;
        this.promotionR01 = promotionR01;
        this.promotionV01 = promotionV01;
        this.promotionR02 = promotionR02;
        this.promotionV02 = promotionV02;
        this.promotionR03 = promotionR03;
        this.promotionV03 = promotionV03;
        this.promotionR04 = promotionR04;
        this.promotionV04 = promotionV04;
        this.promotionR05 = promotionR05;
        this.promotionV05 = promotionV05;
        this.statusId = statusId;
        this.promotionId = promotionId;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedAt = updatedAt;
        this.updatedUser = updatedUser;
        this.deletedAt = deletedAt;
        this.deletedUser = deletedUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPromotionNextStatus() {
        return this.promotionNextStatus;
    }

    public void setPromotionNextStatus(Integer promotionNextStatus) {
        this.promotionNextStatus = promotionNextStatus;
    }

    public Integer getPromotionR01() {
        return this.promotionR01;
    }

    public void setPromotionR01(Integer promotionR01) {
        this.promotionR01 = promotionR01;
    }

    public Integer getPromotionV01() {
        return this.promotionV01;
    }

    public void setPromotionV01(Integer promotionV01) {
        this.promotionV01 = promotionV01;
    }

    public Integer getPromotionR02() {
        return this.promotionR02;
    }

    public void setPromotionR02(Integer promotionR02) {
        this.promotionR02 = promotionR02;
    }

    public Integer getPromotionV02() {
        return this.promotionV02;
    }

    public void setPromotionV02(Integer promotionV02) {
        this.promotionV02 = promotionV02;
    }

    public Integer getPromotionR03() {
        return this.promotionR03;
    }

    public void setPromotionR03(Integer promotionR03) {
        this.promotionR03 = promotionR03;
    }

    public Integer getPromotionV03() {
        return this.promotionV03;
    }

    public void setPromotionV03(Integer promotionV03) {
        this.promotionV03 = promotionV03;
    }

    public Integer getPromotionR04() {
        return this.promotionR04;
    }

    public void setPromotionR04(Integer promotionR04) {
        this.promotionR04 = promotionR04;
    }

    public Integer getPromotionV04() {
        return this.promotionV04;
    }

    public void setPromotionV04(Integer promotionV04) {
        this.promotionV04 = promotionV04;
    }

    public Integer getPromotionR05() {
        return this.promotionR05;
    }

    public void setPromotionR05(Integer promotionR05) {
        this.promotionR05 = promotionR05;
    }

    public Integer getPromotionV05() {
        return this.promotionV05;
    }

    public void setPromotionV05(Integer promotionV05) {
        this.promotionV05 = promotionV05;
    }

    public Integer getStatusId() {
        return this.statusId;
    }

    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
        if (statusId != null) {
            Status status = new Status();
            status.setId(statusId);
            this.statuss = status;
        }
    }

    @JsonIgnore
    public Integer getPromotionId() {
        return this.promotionId;
    }

    @JsonSetter
    public void setPromotionId(Integer promotionId) {
        this.promotionId = promotionId;
        if (promotionId != null) {
            Promotion promotion = new Promotion();
            promotion.setId(promotionId);
            this.promotions = promotion;

        }
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Integer getCreatedUser() {
        return this.createdUser;
    }

    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Integer getDeletedUser() {
        return this.deletedUser;
    }

    public void setDeletedUser(Integer deletedUser) {
        this.deletedUser = deletedUser;
    }

}
