package vn.itt.msales.entity;
// Generated Oct 9, 2015 3:36:35 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * PromotionAwardRef generated by hbm2java
 */
@Entity
@Table(name = "PROMOTION_AWARD_REF"
)
public class PromotionAwardRef implements java.io.Serializable {

    private static final long serialVersionUID = 2274278849818268766L;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    private Integer id;

    @Transient
    private Integer promotionId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PROMOTION_ID", nullable = false)
    private Promotion promotions;

    public Promotion getPromotions() {
        return promotions;
    }

    public void setPromotions(Promotion promotions) {
        this.promotions = promotions;
    }

    @Transient
    private Integer promotionAwardId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PROMOTION_AWARD_ID", nullable = false)
    private PromotionAward promotionAwards;

    public PromotionAward getPromotionAwards() {
        return promotionAwards;
    }

    public void setPromotionAwards(PromotionAward promotionAwards) {
        this.promotionAwards = promotionAwards;
    }

    @Transient
    private Integer promotionGoodsId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PROMOTION_GOODS_ID")
    private Goods promotionGoodss;

    public Goods getPromotionGoodss() {
        return promotionGoodss;
    }

    public void setPromotionGoodss(Goods promotionGoodss) {
        this.promotionGoodss = promotionGoodss;
    }
    @Transient
    private Integer statusId;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "STATUS_ID", nullable = false)
    private Status statuss;

    public Status getStatuss() {
        return statuss;
    }

    public void setStatuss(Status statuss) {
        this.statuss = statuss;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_AT", nullable = false, length = 19)
    private Date createdAt;
    @Column(name = "CREATED_USER", nullable = false)
    private Integer createdUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_AT", length = 19)
    private Date updatedAt;
    @Column(name = "UPDATED_USER", nullable = false)
    private Integer updatedUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DELETED_AT", length = 19)
    private Date deletedAt;
    @Column(name = "DELETED_USER", nullable = false)
    private Integer deletedUser;

    public PromotionAwardRef() {
    }

    public PromotionAwardRef(Integer promotionId, Integer promotionAwardId, Integer statusId, Date createdAt, Integer createdUser, Integer updatedUser, Integer deletedUser) {
        this.promotionId = promotionId;
        this.promotionAwardId = promotionAwardId;
        this.statusId = statusId;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedUser = updatedUser;
        this.deletedUser = deletedUser;
    }

    public PromotionAwardRef(Integer promotionId, Integer promotionAwardId, Integer promotionGoodsId, Integer statusId, Date createdAt, Integer createdUser, Date updatedAt, Integer updatedUser, Date deletedAt, Integer deletedUser) {
        this.promotionId = promotionId;
        this.promotionAwardId = promotionAwardId;
        this.promotionGoodsId = promotionGoodsId;
        this.statusId = statusId;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedAt = updatedAt;
        this.updatedUser = updatedUser;
        this.deletedAt = deletedAt;
        this.deletedUser = deletedUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @JsonIgnore
    public Integer getPromotionId() {
        return this.promotionId;
    }

    @JsonSetter
    public void setPromotionId(Integer promotionId) {
        this.promotionId = promotionId;
        if (promotionId != null) {
            Promotion promotion = new Promotion();
            promotion.setId(promotionId);
            this.promotions = promotion;
        }
    }

    @JsonIgnore
    public Integer getPromotionAwardId() {
        return this.promotionAwardId;
    }

    @JsonSetter
    public void setPromotionAwardId(Integer promotionAwardId) {
        this.promotionAwardId = promotionAwardId;
        if (promotionAwardId != null) {
            PromotionAward promotionAward = new PromotionAward();
            promotionAward.setId(promotionAwardId);
            this.promotionAwards = promotionAward;
        }
    }

    @JsonIgnore
    public Integer getPromotionGoodsId() {
        return this.promotionGoodsId;

    }

    @JsonSetter
    public void setPromotionGoodsId(Integer promotionGoodsId) {
        this.promotionGoodsId = promotionGoodsId;
        if (promotionGoodsId != null) {
            Goods goods = new Goods();
            goods.setId(promotionGoodsId);
            this.promotionGoodss = goods;
        }
    }

    @JsonIgnore
    public Integer getStatusId() {
        return this.statusId;
    }

    @JsonSetter
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
        if (statusId != null) {
            Status status = new Status();
            status.setId(statusId);
            this.statuss = status;
        }
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Integer getCreatedUser() {
        return this.createdUser;
    }

    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Integer getDeletedUser() {
        return this.deletedUser;
    }

    public void setDeletedUser(Integer deletedUser) {
        this.deletedUser = deletedUser;
    }

}
