package vn.itt.msales.entity;
// Generated Oct 9, 2015 3:36:35 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * PromotionAward generated by hbm2java
 */
@Entity
@Table(name = "PROMOTION_AWARD"
)
public class PromotionAward implements java.io.Serializable {

    private static final long serialVersionUID = 5449928601182206917L;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    private Integer id;
    @Column(name = "PROMOTION_AWARD_CODE", nullable = false, length = 64)
    private String promotionAwardCode;
    @Column(name = "PROMOTION_AWARD_NAME", nullable = false, length = 512)
    private String promotionAwardName;
    @Column(name = "PROMOTION_AWARD_DESC", length = 1024)
    private String promotionAwardDesc;

    @Transient
    private Integer statusId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "STATUS_ID", nullable = false)
    private Status statuss;

    public Status getStatuss() {
        return statuss;
    }

    public void setStatuss(Status statuss) {
        this.statuss = statuss;
    }

    @Column(name = "`ORDER`")
    private Integer order;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_AT", nullable = false, length = 19)
    private Date createdAt;
    @Column(name = "CREATED_USER", nullable = false)
    private Integer createdUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_AT", length = 19)
    private Date updatedAt;
    @Column(name = "UPDATED_USER", nullable = false)
    private Integer updatedUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DELETED_AT", length = 19)
    private Date deletedAt;
    @Column(name = "DELETED_USER", nullable = false)
    private Integer deletedUser;

    public PromotionAward() {
    }

    public PromotionAward(Integer id, String promotionAwardCode, String promotionAwardName, Integer statusId, Date createdAt, Integer createdUser, Integer updatedUser, Integer deletedUser) {
        this.id = id;
        this.promotionAwardCode = promotionAwardCode;
        this.promotionAwardName = promotionAwardName;
        this.statusId = statusId;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedUser = updatedUser;
        this.deletedUser = deletedUser;
    }

    public PromotionAward(Integer id, String promotionAwardCode, String promotionAwardName, String promotionAwardDesc, Integer statusId, Integer order, Date createdAt, Integer createdUser, Date updatedAt, Integer updatedUser, Date deletedAt, Integer deletedUser) {
        this.id = id;
        this.promotionAwardCode = promotionAwardCode;
        this.promotionAwardName = promotionAwardName;
        this.promotionAwardDesc = promotionAwardDesc;
        this.statusId = statusId;
        this.order = order;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedAt = updatedAt;
        this.updatedUser = updatedUser;
        this.deletedAt = deletedAt;
        this.deletedUser = deletedUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPromotionAwardCode() {
        return this.promotionAwardCode;
    }

    public void setPromotionAwardCode(String promotionAwardCode) {
        this.promotionAwardCode = promotionAwardCode;
    }

    public String getPromotionAwardName() {
        return this.promotionAwardName;
    }

    public void setPromotionAwardName(String promotionAwardName) {
        this.promotionAwardName = promotionAwardName;
    }

    public String getPromotionAwardDesc() {
        return this.promotionAwardDesc;
    }

    public void setPromotionAwardDesc(String promotionAwardDesc) {
        this.promotionAwardDesc = promotionAwardDesc;
    }

    public Integer getStatusId() {
        return this.statusId;
    }

    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
        if (statusId != null) {
            Status status = new Status();
            status.setId(statusId);
            this.statuss = status;
        }
    }

    public Integer getOrder() {
        return this.order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Integer getCreatedUser() {
        return this.createdUser;
    }

    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getUpdatedUser() {
        return this.updatedUser;
    }

    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Integer getDeletedUser() {
        return this.deletedUser;
    }

    public void setDeletedUser(Integer deletedUser) {
        this.deletedUser = deletedUser;
    }

}
