package vn.itt.msales.entity;

// Generated Jun 22, 2015 9:37:59 AM by Hibernate Tools 4.3.1
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.validation.constraints.NotNull;
import vn.itt.msales.common.json.validator.MsalesValidator;

/**
 * SalesStockGoodsSerial generated by hbm2java
 */
@Entity
@Table(name = "`sales_stock_goods_serial`")
public class SalesStockGoodsSerial implements java.io.Serializable {

    private static final long serialVersionUID = 7060533217844119698L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "SEQ_ID")
    @SequenceGenerator(name = "SEQ_ID", sequenceName = "SEQ_SALESSTOCKGOODSSERIAL_ID")
    @Column(name = "ID", unique = true, nullable = false)
    private Integer id;    
    
    @Transient
    private int stockId;
    @Transient
    private int goodsId;
    @Column(name = "SERIAL", nullable = false, length = 20)
    private String serial;
    @Transient
    private int statusId;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "IMPORTED_DATE", nullable = false, length = 19)
    private Date importedDate;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CHANGED_DATE", nullable = false, length = 19)
    private Date changedDate;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_AT", nullable = false, length = 19)
    private Date createdAt;
    @Column(name = "CREATED_USER", nullable = false)
    private int createdUser;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_AT", length = 19)
    @JsonIgnore
    private Date updatedAt;

    @Column(name = "UPDATED_USER", nullable = false)
    @NotNull(message = MsalesValidator.UPDATED_USER_NULL)
    private Integer updatedUser;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DELETED_AT", length = 19)
    @JsonIgnore
    private Date deletedAt;

    @Column(name = "DELETED_USER", nullable = false)
    @NotNull(message = MsalesValidator.DELETED_USER_NULL)
    private Integer deletedUser;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "GOODS_ID", nullable = false)
    private Goods goods;

    @JsonIgnoreProperties(value = {"parentId", "goodsCode", "statusId",
        "isRecover", "price", "factor", "isFocus", "order", "goodsCategory"})
    public Goods getGoods() {
        return goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "STATUS_ID", nullable = false)
    private Status status;

    @JsonIgnoreProperties(value = {"value", "statusType"})
    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "STOCK_ID", nullable = false)
    private SalesStock stock;

    @JsonIgnoreProperties(value = {"statusId"})
    public SalesStock getStock() {
        return stock;
    }

    public void setStock(SalesStock stock) {
        this.stock = stock;
    }

    public SalesStockGoodsSerial() {
    }

    public SalesStockGoodsSerial(int stockId, int goodsId, String serial,
            int statusId, Date importedDate, Date changedDate, Date createdAt,
            int createdUser, Date updatedAt, int updatedUser, Date deletedAt,
            int deletedUser) {
        this.stockId = stockId;
        this.goodsId = goodsId;
        this.serial = serial;
        this.statusId = statusId;
        this.importedDate = importedDate;
        this.changedDate = changedDate;
        this.createdAt = createdAt;
        this.createdUser = createdUser;
        this.updatedAt = updatedAt;
        this.updatedUser = updatedUser;
        this.deletedAt = deletedAt;
        this.deletedUser = deletedUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    // @Column(name="STOCK_ID", nullable=false)
    @JsonIgnore
    public int getStockId() {
        return this.stockId;
    }

    @JsonSetter
    public void setStockId(int stockId) {
        this.stockId = stockId;
        SalesStock salesStock = new SalesStock();
        salesStock.setId(this.getStockId());
        this.setStock(salesStock);
    }

    // @Column(name="GOODS_ID", nullable=false)
    @JsonIgnore
    public int getGoodsId() {
        return this.goodsId;
    }

    @JsonSetter
    public void setGoodsId(int goodsId) {
        this.goodsId = goodsId;
        Goods goods = new Goods();
        goods.setId(this.getGoodsId());
        this.setGoods(goods);
    }

    public String getSerial() {
        return this.serial;
    }

    public void setSerial(String serial) {
        this.serial = serial;
    }

    // @Column(name="STATUS_ID", nullable=false)
    @JsonIgnore
    public int getStatusId() {
        return this.statusId;
    }

    @JsonSetter
    public void setStatusId(int statusId) {
        this.statusId = statusId;
        Status status = new Status();
        status.setId(this.getStatusId());
        this.setStatus(status);
    }

    public Date getImportedDate() {
        return this.importedDate;
    }

    public void setImportedDate(Date importedDate) {
        this.importedDate = importedDate;
    }

    public Date getChangedDate() {
        return this.changedDate;
    }

    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }

    @JsonIgnore
    public Date getCreatedAt() {
        return this.createdAt;
    }

    @JsonSetter
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @JsonIgnore
    public int getCreatedUser() {
        return this.createdUser;
    }

    @JsonSetter
    public void setCreatedUser(int createdUser) {
        this.createdUser = createdUser;
    }

    @JsonIgnore
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    @JsonSetter
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @JsonIgnore
    public int getUpdatedUser() {
        return this.updatedUser;
    }

    @JsonSetter
    public void setUpdatedUser(int updatedUser) {
        this.updatedUser = updatedUser;
    }

    @JsonIgnore
    public Date getDeletedAt() {
        return this.deletedAt;
    }

    @JsonSetter
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    @JsonIgnore
    public int getDeletedUser() {
        return this.deletedUser;
    }

    @JsonSetter
    public void setDeletedUser(int deletedUser) {
        this.deletedUser = deletedUser;
    }

}
