package vn.itt.msales.entity.searchObject;

// Generated Oct 23, 2012 8:21:15 PM by Hibernate Tools 3.4.0.CR1

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;


/**
 * LoTrinh generated by hbm2java
 */
public class LoTrinhForMap implements java.io.Serializable {
	private static final long serialVersionUID = 3293675195247547203L;

//	private long id;
	private String ngayGio;
	private Double kinhDo;
	private Double viDo;
//	private String soImei;
//	private String subcriberId;
//	private Long maSoNhanVien;
	private static SimpleDateFormat dformat = new SimpleDateFormat(
			"dd/MM/yy HH:mm:ss");

	public LoTrinhForMap() {
	}
	
	public LoTrinhForMap(LoTrinh loTrinh) {
//		this.id = loTrinh.getId();
		java.util.Calendar ngayGio = loTrinh.getNgayGio();
		
		if (ngayGio != null)
			this.ngayGio = dformat.format(ngayGio.getTime());
		
		//this.ngayGio = ngayGio;
		this.kinhDo = loTrinh.getKinhDo();
		this.viDo = loTrinh.getViDo();
//		this.soImei = loTrinh.getSoImei();
//		this.subcriberId = loTrinh.getSubcriberId();
//		this.maSoNhanVien = loTrinh.getMaSoNhanVien();
	}

	public LoTrinhForMap(long id, String ngayGio, Double kinhDo, Double viDo,
			String soImei, String subcriberId) {
//		this.id = id;
		this.ngayGio = ngayGio;
		this.kinhDo = kinhDo;
		this.viDo = viDo;
//		this.soImei = soImei;
//		this.subcriberId = subcriberId;
	}

	public LoTrinhForMap(long id, String ngayGio, Double kinhDo, Double viDo,
			String soImei, String subcriberId, Long maSoNhanVien) {
//		this.id = id;
		this.ngayGio = ngayGio;
		this.kinhDo = kinhDo;
		this.viDo = viDo;
//		this.soImei = soImei;
//		this.subcriberId = subcriberId;
//		this.maSoNhanVien = maSoNhanVien;
	}

//	public long getId() {
//		return this.id;
//	}
//
//	public void setId(long id) {
//		this.id = id;
//	}

	public String getNgayGio() {
		return this.ngayGio;
	}

	public void setNgayGio(String ngayGio) {
		this.ngayGio = ngayGio;
	}

	public Double getKinhDo() {
		return this.kinhDo;
	}

	public void setKinhDo(Double kinhDo) {
		this.kinhDo = kinhDo;
	}

	public Double getViDo() {
		return this.viDo;
	}

	public void setViDo(Double viDo) {
		this.viDo = viDo;
	}

//	public String getSoImei() {
//		return this.soImei;
//	}
//
//	public void setSoImei(String soImei) {
//		this.soImei = soImei;
//	}
//
//	public String getSubcriberId() {
//		return this.subcriberId;
//	}
//
//	public void setSubcriberId(String subcriberId) {
//		this.subcriberId = subcriberId;
//	}

//	public Long getMaSoNhanVien() {
//		return this.maSoNhanVien;
//	}
//
//	public void setMaSoNhanVien(Long maSoNhanVien) {
//		this.maSoNhanVien = maSoNhanVien;
//	}

}
