package vn.itt.msales.entity.searchObject;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

// Generated Oct 23, 2012 8:21:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * LoTrinh generated by hbm2java
 */
@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
@JsonFilter("JSONFILTER")
public class LoTrinh implements java.io.Serializable {
	private static final long serialVersionUID = 3293675195247547203L;

	private long id;
	private java.util.Calendar ngayGio;
	private Double kinhDo;
	private Double viDo;
	private String soImei;
	private String viTri;
	private String subcriberId;
	private Long maSoNhanVien;
	private String tenNV;

	public LoTrinh() {
	}

	public LoTrinh(long id, java.util.Calendar ngayGio, Double kinhDo, Double viDo,
			String soImei, String subcriberId ,String  viTri) {
		this.id = id;
		this.ngayGio = ngayGio;
		this.kinhDo = kinhDo;
		this.viDo = viDo;
		this.soImei = soImei;
		this.subcriberId = subcriberId;
		this.viTri = viTri;
	}

	public LoTrinh(long id, java.util.Calendar ngayGio, Double kinhDo, Double viDo,
			String soImei, String subcriberId, Long maSoNhanVien,String  viTri) {
		this.id = id;
		this.ngayGio = ngayGio;
		this.kinhDo = kinhDo;
		this.viDo = viDo;
		this.soImei = soImei;
		this.subcriberId = subcriberId;
		this.maSoNhanVien = maSoNhanVien;
		this.viTri = viTri;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public java.util.Calendar getNgayGio() {
		return this.ngayGio;
	}

	public void setNgayGio(java.util.Calendar ngayGio) {
		this.ngayGio = ngayGio;
	}

	public Double getKinhDo() {
		return this.kinhDo;
	}

	public void setKinhDo(Double kinhDo) {
		this.kinhDo = kinhDo;
	}

	public Double getViDo() {
		return this.viDo;
	}

	public void setViDo(Double viDo) {
		this.viDo = viDo;
	}

	public String getSoImei() {
		return this.soImei;
	}

	public void setSoImei(String soImei) {
		this.soImei = soImei;
	}

	public String getSubcriberId() {
		return this.subcriberId;
	}

	public void setSubcriberId(String subcriberId) {
		this.subcriberId = subcriberId;
	}

	public Long getMaSoNhanVien() {
		return this.maSoNhanVien;
	}

	public void setMaSoNhanVien(Long maSoNhanVien) {
		this.maSoNhanVien = maSoNhanVien;
	}
	
	public String getViTri() {
		return this.viTri;
	}

	public void setViTri(String viTri) {
		this.viTri = viTri;
	}

	public String getTenNV() {
		return tenNV;
	}

	public void setTenNV(String tenNV) {
		this.tenNV = tenNV;
	}

	
}
